# µblog API settings

# Public URL
# Publicly exposed URL for your µblog site
publicUrl: "http://blog.example.com"

# Allowed Hosts
# List of hosts allowed to connect to API server directly
allowedHosts: "*"

# DB Connection Strings
connectionStrings:
  defaultConnection: "Server=127.0.0.1;Port=5432;Database=myDataBase;User Id=myUsername;Password=myPassword;"

# Serilog Configuration
# Configuration for logging with Serilog
# https://github.com/serilog/serilog-settings-configuration
serilog:
  minimumLevel:
    default: "Information"
  using:
    - "Serilog.Sinks.Console"
  #    - "Serilog.Sinks.File"
  writeTo:
    - name: "Console"
  #    - Name: "File"
  #      Args: 
  #        path: "Logs/log.txt"
  enrich:
    - "FromLogContext"
  properties:
    application: "µblog-server"